import 'dotenv/config';

export default {
  token: process.env.BOT_TOKEN || "",
  clientId: process.env.CLIENT_ID || "",
  guildId: process.env.GUILD_ID || "",
  ownerId: process.env.OWNER_ID || "",
  prefix: "!",
  brand: {
    name: "AERIX",
    tagline: "Next-Gen Server Security & Management",
    version: "2.0.0",
  },
  colors: {
    primary: 0x00F0FF,
    gold: 0xFFD700,
    success: 0x00FF88,
    error: 0xFF0044,
    warning: 0xFFAA00,
    info: 0x0088FF,
    dark: 0x0A0A1A,
    navy: 0x0D1B2A,
    purple: 0xBB00FF,
    pink: 0xFF0088,
    neon: 0x39FF14,
    cyber: 0x00F0FF,
    blurple: 0x5865F2,
    embedBg: 0x0A0A1A,
  },
  emoji: {
    check: "✅",
    cross: "❌",
    warning: "⚠️",
    error: "❌",
    success: "✅",
    info: "ℹ️",
    loading: "⏳",
    ticket: "🎫",
    crown: "👑",
    boost: "🚀",
    online: "🟢",
    idle: "🟡",
    dnd: "🔴",
    offline: "⚫",
    stream: "📺",
    nitro: "⭐",
    developer: "💻",
    mod: "🛡️",
    owner: "👑",
    admin: "🔧",
    member: "👤",
    bot: "🤖",
    text: "💬",
    voice: "🔊",
    announcement: "📢",
    link: "🔗",
    stats: "📊",
    settings: "⚙️",
    level: "📈",
    xp: "✨",
    coin: "🪙",
    bank: "🏦",
    shop: "🛒",
    gift: "🎁",
    giveaway: "🎉",
    party: "🎊",
    fun: "🎮",
    moderation: "🛠️",
    utility: "🔧",
    music: "🎵",
    search: "🔍",
    list: "📋",
    write: "✍️",
    trash: "🗑️",
    edit: "📝",
    lock: "🔒",
    unlock: "🔓",
    mute: "🔇",
    unmute: "🔊",
    ban: "🔨",
    kick: "👢",
    warn: "📄",
    invite: "📨",
    support: "🆘",
    vote: "📮",
    youtube: "▶️",
    twitter: "🐦",
    instagram: "📷",
    github: "🐙",
    reddit: "🤖",
    discord: "💬",
    spotify: "🎧",
    twitch: "📺",
    ping: "📶",
    time: "⏰",
    calendar: "📅",
    trophy: "🏆",
    medal: "🏅",
    star: "⭐",
    heart: "❤️",
    fire: "🔥",
    antinuke: "🛡️",
    shield: "🛡️",
    radar: "📡",
    terminal: "💻",
    globe: "🌐",
    dashboard: "📊",
    security: "🔐",
  },
  economy: {
    dailyAmount: 500,
    weeklyAmount: 2500,
    monthlyAmount: 10000,
    workMin: 50,
    workMax: 200,
    robFailChance: 0.4,
    interestRate: 0.05,
    maxBankSpace: 100000,
    slotCost: 50,
    slotPayout: 500,
    gambleMin: 10,
    gambleMax: 10000,
    lotteryTicket: 100,
    lotteryPoolShare: 0.7,
    hourlyMin: 20,
    hourlyMax: 80,
  },
  tickets: {
    categoryName: "Tickets",
    supportRoleName: "Support Team",
    maxTicketsPerUser: 3,
    transcriptEnabled: true,
  },
  automod: {
    defaultMaxCaps: 0.7,
    defaultMaxMentions: 5,
    defaultMaxEmoji: 10,
    defaultMaxLines: 5,
    defaultMaxNewlines: 3,
    defaultMaxDuplicates: 5,
  },
  antinuke: {
    enabled: true,
    maxBansPerMinute: 3,
    maxKicksPerMinute: 3,
    maxChannelDeletesPerMinute: 2,
    maxChannelCreatesPerMinute: 3,
    maxRoleDeletesPerMinute: 2,
    maxRoleCreatesPerMinute: 3,
    whitelistedUsers: [],
    whitelistedRoles: [],
    punishAction: "ban",
    logChannel: null,
  },
  levels: {
    xpPerMessage: 15,
    xpVoicePerMinute: 10,
    xpCooldown: 60000,
    baseLevelXp: 100,
    levelXpMultiplier: 1.5,
    maxLevel: 1000,
    levelUpChannel: null,
    levelUpMessage: "GG {member}, you reached level **{level}**!",
    stackRoles: true,
  },
  waitlistUpdateInterval: 60000,
  music: {
    defaultVolume: 50,
    maxQueueSize: 500,
    timeout: 300000,
  },
  lavalink: {
    nodes: [
      { name: 'Jirayu', host: 'lavalink.jirayu.net', port: 13592, auth: 'youshallnotpass' },
    ],
  },
  logging: {
    defaultEvents: ["messageDelete", "messageEdit", "memberJoin", "memberLeave", "memberBan", "memberUnban", "voiceJoin", "voiceLeave", "voiceMove", "channelCreate", "channelDelete", "roleCreate", "roleDelete"],
  },
  verification: {
    enabled: false,
    roleName: "Verified",
    logEnabled: true,
  },
  counting: {
    enabled: false,
    maxCount: 1000000,
  },
};
